ZoneInfoNotFoundError: No time zone found with key Asia/Beijing (#2697)
* create TIMEZONE_FALLBACKS dictoniary
create _get_valid_timezone

* rework _get_valid_timezone

* update doc string
change except because KeyError is not actual

* added _warn message

* added _warn message with e

* fix by ruff